# Site settings
title: Hammy Assassin
email: 
description: Surfer / iOS Developer / Swimmer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: HammyAssassin
github_username:  HamstringAssassin

avatar: face.png

bg-img: hero-bg.jpg
logo: logo.svg

blurb: <p><strong>Alan specializes in making iOS Apps.</strong> He loves to code in both Objective-C and Swift. He also dables in web design and likes to think that he has a good eye for aesthetics.</p><p>When hes not building beautiful, powerful, clean, award-winning apps, he can be found near large bodies of water. He loves surfing and has been known to drive for 8 hours to the Atlantic ocean to surf some of the most beautiful locations Ireland has to offer. He's also a competitive swimmer. So asking about water sports is a way to never shut him up. :) </p><p>For more on Al, you can catch him up <a href="https://twitter.com/HammyAssassin">here</a>...</p>

# Build settings
markdown: kramdown

port: 8080
# Build settings

permalink: pretty

sass:
  sass_dir:   assets/css
  style: :nested