# Site settings
title: hamstringassassin.github.io
email: 
description: > # this means to ignore newlines until "baseurl:"
  Can be found near large bodies of water or in front of xCode. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: HammyAssassin
github_username:  HamstringAssassin

# Build settings
markdown: kramdown

port: 8080
# Build settings

permalink: pretty

sass:
  sass_dir: assets/css
  style: :nested